### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: closed

### ISSUE THREAD

**Issue by liutingdu** [eoinsha/JavaPhoenixChannels#21]
I am using the Phoenix channel in my Android app and here is the code: https://github.com/evercam/evercam-play-android/blob/master/evercamPlay/src/main/java/io/evercam/androidapp/tasks/LiveViewRunnable.java

Crashlytics was integrated for tracking app crashes, and I'm keep getting this error:

```
Fatal Exception: java.lang.IllegalStateException: closed
       at com.squareup.okhttp.internal.ws.RealWebSocket.close(RealWebSocket.java:164)
       at org.phoenixframework.channels.Socket$PhoenixWSListener.onFailure(Socket.java:130)
       at com.squareup.okhttp.internal.ws.RealWebSocket.readerErrorClose(RealWebSocket.java:217)
       at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:100)
       at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:153)
       at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
       at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
       at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
       at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

But I couldn't find a way to reproduce it in my app.

Any idea about the reason why it's happening? What's the suggested solution for handling errors like this?

Thanks,
Liuting

**Comment by bryanjos** [comment]
Hi, is this still an issue for you? Did any of the updates since resolve it?

**Comment by liutingdu** [comment]
@bryanjos Sorry I didn't look into it further as I no longer work on that project. Will close this issue since it's not a common problem. Thanks anyway!
