### ISSUE TITLE
JavaPhoenixChannels not working on Phoenix 1.1.0

### ISSUE THREAD

**Issue by ttpho** [eoinsha/JavaPhoenixChannels#4]
When we changed Phoenix 1.0.x to 1.1.0, JavaPhoenixChannels not working

after hooks have been replaced by a timeout option on push, and a receive("timeout", callback) hook.

// 1.0.x
channel.push("new_message", {body: "hi!"})
       .receive("ok", resp => console.log(resp) )
       .after(5000, () => console.log("times! up"))

channel.push("new_message", {body: "hi!"})
       .receive("ok", resp => console.log(resp) )
       .after(12000, () => console.log("times! up"))

// 1.1.0
// timeout default to 5000
channel.push("new_message", {body: "hi!"}) 
       .receive("ok", resp => console.log(resp) )
       .receive("timeout", () => console.log("times! up"))

This is message log
 W/Socket: WebSocket connection error
                                                 java.io.EOFException
                                                     at okio.RealBufferedSource.require(RealBufferedSource.java:64)
                                                     at okio.RealBufferedSource.readByte(RealBufferedSource.java:77)
                                                     at com.squareup.okhttp.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:108)
                                                     at com.squareup.okhttp.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
                                                     at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:87)
                                                     at com.squareup.okhttp.ws.WebSocketCall$2.execute(WebSocketCall.java:187)
                                                     at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                     at java.lang.Thread.run(Thread.java:856)
 W/Socket: Failed to explicitly close following failure

**Comment by bryanjos** [comment]
Not sure if this is related to #3 or not. From talking with Chris McCord it sounds like the client itself should still be compatible with 1.0. I'm looking into it now to see if I can't get it working.

**Comment by steffenix** [comment]
@ttpho @bryanjos did you find a way to have it work on 1.1.0?

**Comment by ttpho** [comment]
@steffenix: it's not working
WebSocket connection error
java.io.EOFException
at okio.RealBufferedSource.require(RealBufferedSource.java:64)
at okio.RealBufferedSource.readByte(RealBufferedSource.java:77)
at com.squareup.okhttp.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:108)
at com.squareup.okhttp.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:87)
at com.squareup.okhttp.ws.WebSocketCall$2.execute(WebSocketCall.java:187)
at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
at java.lang.Thread.run(Thread.java:856)
W/Socket: Failed to explicitly close following failure

**Comment by bryanjos** [comment]
@ttpho @bryanjos I think it's a timeout error. I sent a PR to implement heartbeat which was merged, but looks like it wasn't working properly. There is another PR right now, #11 that hopefully should resolve it
