### ISSUE TITLE
SocketTimeoutException

### ISSUE THREAD

**Issue by hopewise** [eoinsha/JavaPhoenixChannels#43]
if I connect locally, it works fine, but, if I connect to the server on cloud, I get this error:

> W/Socket: WebSocket connection error
>           java.net.SocketTimeoutException
>               at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
>               at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
>               at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
>               at okio.Okio$2.read(Okio.java:139)
>               at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
>               at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
>               at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
>               at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
>               at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
>               at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
>               at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
>               at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:573)
>               at com.squareup.okhttp.Call.getResponse(Call.java:287)
>               at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
>               at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
>               at com.squareup.okhttp.Call.access$100(Call.java:35)
>               at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171)
>               at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
>               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
>               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
>               at java.lang.Thread.run(Thread.java:818)

I am not using proxy or load balancer, why I get this error? how can debug this?

**Comment by hopewise** [comment]
Fixed, it was a problem in my app
