### ISSUE TITLE
JavaPhoenixChannels + Okhttp3 v3.8.1

### ISSUE THREAD

**Issue by nicolkill** [eoinsha/JavaPhoenixChannels#59]
I need use okttp for api calls and use the channels, but on connect throws the next exception

```
FATAL EXCEPTION: main
Process: com.yetcargo.yetcargotracker.dev, PID: 20196
java.lang.NoSuchMethodError: No virtual method setCallWebSocket(Lokhttp3/Call;)V in class Lokhttp3/internal/Internal; or its super classes (declaration of 'okhttp3.internal.Internal' appears in /data/app/com.yetcargo.yetcargotracker.dev-1/split_lib_dependencies_apk.apk:classes73.dex)
at okhttp3.ws.WebSocketCall.enqueue(WebSocketCall.java:108)
at org.phoenixframework.channels.Socket.connect(Socket.java:204)
at com.yetcargo.yetcargotracker.screens.main.AllwaysThereService.onStartCommand(AllwaysThereService.java:102)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3394)
at android.app.ActivityThread.-wrap21(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1632)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:203)
at android.app.ActivityThread.main(ActivityThread.java:6251)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

**Comment by RustamG** [comment]
@nicolkill How did you solve this?

**Comment by nicolkill** [comment]
copy the project and add them to your project and adjust the dependencies
