### ISSUE TITLE
E/Socket: Failed to read message payload

### ISSUE THREAD

**Issue by P-r-a-d-e-e-P** [eoinsha/JavaPhoenixChannels#63]
Hi, I'm using the library for android client. While joining the channel and on every event I get the following error. The functionality works fine without any issues as the payload is getting delivered to the call backs. 

Kindly advice how this exception can be handled.

E/Socket: Failed to read message payload
                                                                        com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "join_ref" (class org.phoenixframework.channels.Envelope), not marked as ignorable (4 known properties: "event", "ref", "payload", "topic"])
                                                                            at [Source: buffer(okhttp3.internal.ws.WebSocketReader$FramedMessageSource@9999fee).inputStream(); line: 1, column: 86] (through reference chain: org.phoenixframework.channels.Envelope["join_ref"])
                                                                            at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:834)
                                                                            at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1096)
                                                                            at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1469)
                                                                            at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1447)
                                                                            at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:282)
                                                                            at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
                                                                            at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
                                                                            at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2899)
                                                                            at org.phoenixframework.channels.Socket$PhoenixWSListener.onMessage(Socket.java:80)
                                                                            at okhttp3.internal.ws.RealWebSocket$1.onMessage(RealWebSocket.java:62)
                                                                            at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:242)
                                                                            at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:108)
                                                                            at okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
                                                                            at okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152)
                                                                            at okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
                                                                            at okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
                                                                            at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
                                                                            at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)

**Comment by MContagious** [comment]
@P-r-a-d-e-e-P check the following pull request

https://github.com/eoinsha/JavaPhoenixChannels/pull/64
